# Pipeline do wdrożenia aplikacji z wcześniej zbudowanego artefaktu ZIP

trigger: none  # Ten pipeline uruchamiany jest ręcznie lub z innego pipeline

pool:
  vmImage: 'windows-latest'

steps:
  # Pobranie artefaktów ZIP z pipeline builda
  #- task: DownloadPipelineArtifact@2
    #inputs:
      #artifactName: 'drop'
      #targetPath: '$(Pipeline.Workspace)/drop'
    #displayName: 'Download artifacts'

    # Krok 1: Pobranie artefaktów ZIP z OSTATNIEGO udanego uruchomienia build pipeline
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'hus'  # <- Nazwa twojego projektu DevOps
      pipeline: 'azure-build-app'  # <- Nazwa build pipeline (musi się zgadzać!)
      buildVersionToDownload: 'latest'
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/drop'
    displayName: 'Download latest artifacts from azure-build-app'

  # Ustawienie zmiennej BUILD_VERSION w App Settings Web Appa
  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'Road2Senior-NewConnection2025'
      resourceGroupName: 'hus-dev'
      appName: 'apifootball-web'
      appSettings: >
        {
          "BUILD_VERSION": "$(Build.BuildNumber)"
        }
    displayName: 'Set BUILD_VERSION in App Service'

  # Wdrożenie aplikacji do Azure Web App
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Road2Senior-NewConnection2025'
      appType: 'webApp'
      appName: 'apifootball-web'
      package: '$(Pipeline.Workspace)/drop/publish.zip'
    displayName: 'Deploy to Azure Web App'
