# Pipeline do uruchamiania Terraform i provisionowania infrastruktury

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: infra-secrets  # <-- Twoja grupa zmiennych

steps:
  # Instalacja .NET (opcjonalnie, jeżeli np. budujesz coś lokalnie)
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Uruchomienie Terraform
  - task: AzureCLI@2
    displayName: 'Run Terraform Init & Apply'
    inputs:
      azureSubscription: 'Road2Senior-NewConnection2025'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        cd $(System.DefaultWorkingDirectory)/terraform
        terraform init -reconfigure \
          -backend-config="resource_group_name=hus-dev" \
          -backend-config="storage_account_name=tfstatehubert001" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate"
        terraform apply -auto-approve \
          -var="sql_admin_login=$(sql_admin_login)" \
          -var="sql_admin_password=$(sql_admin_password)" \
          -var="tenant_id=$(tenant_id)" \
          -var="azure_devops_pat=$(azure_devops_pat)" \
          -var="github_pat=$(github_pat)"
