# Pipeline do budowania aplikacji .NET 8, uruchamiania testów i publikacji artefaktów ZIP

trigger:
  branches:
    include:
      - master
      - feature/*  # buduje też feature branche

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'  # Używanie maszyny z Windows

variables:
  solution: '**/*.sln'  # Ścieżka do pliku .sln
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  AZURE_CLIENT_ID: $(azureClientId)
  AZURE_CLIENT_SECRET: $(azureClientSecret)
  AZURE_TENANT_ID: $(azureTenantId)

steps:
  # Krok 1: Instalacja .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.203'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Krok 2: Pobieranie sekretów z Azure Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Road2Senior-NewConnection2025'
      KeyVaultName: 'apifootballkv'
      SecretsFilter: '*'
      RunAsPreJob: true

  # Krok 3: Restore dependencies
  - script: |
      dotnet restore
    displayName: 'Restore dependencies'

  # Krok 4: Build
  - script: |
      dotnet build --configuration $(buildConfiguration)
    displayName: 'Build project'

  - script: |
      echo "AZURE_CLIENT_ID: %AZURE_CLIENT_ID%"
      echo "AZURE_CLIENT_SECRET: %AZURE_CLIENT_SECRET%"
      echo "AZURE_TENANT_ID: %AZURE_TENANT_ID%"
      echo "$(azureClientId) | $(azureClientSecret) | $(azureTenantId)"
    displayName: "Debug env"
    env:
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)

  # Krok 5: Testy jednostkowe
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
    displayName: 'Run tests'
    env:
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)

  # Krok 6: Publikacja projektu
  - script: |
      dotnet publish "$(Build.SourcesDirectory)/Road2Senior/Road2Senior.csproj" --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
    displayName: 'Publish app'

  # Krok 7: Zip publikacji
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/publish.zip'
      replaceExistingArchive: true
    displayName: 'Zip published files'

  # Krok 8: Publikacja artefaktów
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish.zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish artifacts'
