version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: road2senior-mssql-container
    environment:
      SA_PASSWORD: "MyStrong@Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mssql_data: