# Pipeline do wdrożenia aplikacji z wcześniej zbudowanego artefaktu ZIP

trigger: none  # Uruchamiany ręcznie

parameters:
  - name: buildRunId
    displayName: 'Numer builda (Run ID)'
    type: string
    default: '76'  # <-- Możesz zmieniać ręcznie przy uruchomieniu pipeline'a

pool:
  vmImage: 'windows-latest'

steps:
  # Pobranie artefaktów ZIP z konkretnego builda
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: 'hus'  # <-- podaj nazwę projektu DevOps jeśli inny
      pipeline: 'azure-build-app'
      runVersion: 'specific'
      runId: ${{ parameters.buildRunId }}
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/drop'
    displayName: 'Download artifacts from azure-build-app'

  # Ustawienie BUILD_VERSION w AppSettings
  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'Road2Senior-NewConnection2025'
      resourceGroupName: 'hus-dev'
      appName: 'apifootball-web'
      appSettings: >
        {
          "BUILD_VERSION": "${{ parameters.buildRunId }}"
        }
    displayName: 'Set BUILD_VERSION in App Service'

  # Wdrożenie aplikacji do Azure Web App
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Road2Senior-NewConnection2025'
      appType: 'webApp'
      appName: 'apifootball-web'
      package: '$(Pipeline.Workspace)/drop/publish.zip'
    displayName: 'Deploy to Azure Web App'
